version: '3'
services:
  hadoop-master1:
    image: hd-container:1.0
    hostname: hadoop-master1
    ports:
      - 8088:8088
      - 8042:8042
      - 10000:10000
      - 50070:50070
    volumes:
      - ~/Dev/big-data/hadoop-3.1.2:/opt/bigdata/hadoop
      - ./etc/hadoop:/etc/hadoop
      - ~/Dev/big-data/apache-hive-3.1.2-bin:/opt/bigdata/hive
      - ./etc/hive:/etc/hive
      - ./env/bigdata_env.sh:/etc/profile.d/bigdata_env.sh
  hadoop-slave1:
    image: hd-container:1.0
    hostname: hadoop-slave1
    ports:
      - 8043:8042
    volumes:
      - ~/Dev/big-data/hadoop-3.1.2:/opt/bigdata/hadoop
      - ./etc/hadoop:/etc/hadoop
      - ./env/bigdata_env.sh:/etc/profile.d/bigdata_env.sh
  hadoop-slave2:
    image: hd-container:1.0
    hostname: hadoop-slave2
    ports:
      - 8044:8042
    volumes:
      - ~/Dev/big-data/hadoop-3.1.2:/opt/bigdata/hadoop
      - ./etc/hadoop:/etc/hadoop
      - ./env/bigdata_env.sh:/etc/profile.d/bigdata_env.sh
  zeppelin:
    image: hd-container:1.0
    hostname: zeppelin
    ports:
      - 18080:18080
    volumes:
      - ~/Dev/big-data/zeppelin-0.8.2-bin-netinst:/opt/bigdata/zeppelin